### PR TITLE
Add support for MySQL/MariaDB

### LINKED ISSUE #85: Support myxql
Hi,

I wondered if you are interested in supporting myxql as well. I already got it to run and with a bit of polishing I could create a PR.

### PR DESCRIPTION
**Pull request by phihos**
This PR adds support for the Exto adapter `Ecto.Adapters.MyXQL`.

Closes #85.

### CODE REVIEW

**Comment by phihos** [comment]
I ran the tests locally and they passed. Someone needs tot trigger the CI so I can fix potential CI issues.

**Comment by crbelaus** [comment]
Thanks for this PR @phihos! It looks great, I will take a deeper look later this week. Apparently GitHub Actions doesn't like the `--connect` parameter and the CI is failing.

**Comment by phihos** [comment]
Fixed the formatting issue. Next run should at least go to the database tests.

**Comment by phihos** [comment]
I forgot a line in the example test config which I put in my local test config. The tables should exist now. @crbelaus Can you trigger CI again?

**Comment by phihos** [comment]
I also accidentally reverted the formatter fix from yesterday :see_no_evil: 
Fixed it now.

**Comment by phihos** [comment]
Finally :partying_face:

**Review by crbelaus — APPROVED** [review]
Honestly this is looking great. I've been playing with it and it works flawlessly. Thanks for the work @phihos 

Any thoughts @odarriba ?

**Review by odarriba — APPROVED** [review]
Looks good!! Thanks for this amazing contribution ❤️

**Comment by phihos** [comment]
Thank you for merging my PR. Now I do not have to maintain a fork for my use-case. Your code was already very well structured and implementation went smoothly. Looking forward to future releases :-)

**Comment by crbelaus** [comment]
> Thank you for merging my PR. Now I do not have to maintain a fork for my use-case. Your code was already very well structured and implementation went smoothly. Looking forward to future releases :-)

Thank you for contributing @phihos! BTW, we have just released [v0.3.0](https://github.com/elixir-error-tracker/error-tracker/releases/tag/v0.3.0) with MySQL/MariaDB support.

**Pull request merged**
